repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-builtin-literals
      - id: check-symlinks
      - id: double-quote-string-fixer
      - id: mixed-line-ending
        args: ['--fix=no']

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    -   id: add-trailing-comma

  - repo: local
    hooks:
      - id: tests
        name: pre-commit-tests
        entry: env make lint.fix
        pass_filenames: false
        language: system
        verbose: false
