"""Add breed_name in Order

Revision ID: 159438923edd
Revises: 99ce70a6adda
Create Date: 2024-04-19 00:23:14.309882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159438923edd'
down_revision = '99ce70a6adda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('breed_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'breed_name')
    # ### end Alembic commands ###
