"""Create default executors

Revision ID: 99ce70a6adda
Revises: e9d49ed4384a
Create Date: 2024-04-18 23:39:53.115034

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '99ce70a6adda'
down_revision = 'e9d49ed4384a'
branch_labels = None
depends_on = None

executors = [
	{
		"username": "Пётр"
	},
	{
		"username": "Антон"
	}
]


def upgrade():
	bind = op.get_bind()

	update_query = sa.text(
		"""
			INSERT INTO executors (username)
			VALUES (:username);
		""",
	)

	# Добавляем трек
	for i_executor in executors:
		bind.execute(
			update_query,
			{
				'username': i_executor['username'],
			},
		)


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###
